version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gittion-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
    networks:
      - gittion-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add ngrok for exposing the webhook in development
  ngrok:
    image: ngrok/ngrok:latest
    container_name: gittion-ngrok
    ports:
      - "4040:4040"
    command: "http app:5000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
    depends_on:
      - app
    networks:
      - gittion-network

networks:
  gittion-network:
    driver: bridge

volumes:
  logs:
